spring:
  kafka:
    bootstrap-servers: 10.132.126.155:32771
    consumer:
      group-id: history
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        max.block.ms: 1000
    properties:
      request.timeout.ms: 100

serverConfig:
  history:
    port: 8083

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.ccreanga: WARN
    org.apache.kafka: WARN
    root: ERROR
